---
- name: This sets up an httpd webserver
  #hosts: 192.168.0.19
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  become: yes
  vars_files:
   - vars/defaults.yml
  
  tasks:
  - name: Install apache packages 
    yum:
      name: httpd
      state: present
      
  - name: ensure httpd is running
    service:
      name: httpd 
      state: started
  
  ############# firewalld #############
  #- name: Open port 80 for http access
  #  firewalld:
  #    service: http
  #    permanent: true
  #    state: enabled
  #- name: Restart the firewalld service to load in the firewall changes
  #  service: 
  #    name: firewalld 
  #    state: restarted
