---
- name: This sets up an httpd webserver
  hosts: 127.0.0.1
  gather_facts: no
  connection: local
  
  tasks:
  - name: Install apache packages   
    command: sudo /bin/yum -y install httpd
  - name: Ensure httpd is running
    service:
      name: httpd 
      state: started
    become: true
    
  tasks:
  - name: Create Virtual Host configuration file in /etc/httpd/sites-available
    copy:
      dest: "/etc/httpd/sites-available/{{ lookup('env','ALIAS') }}.{{ lookup('env','SERVER_NAME') }}.conf"
      content: |
        <VirtualHost *:80>
          ServerName {{ lookup('env','SERVER_NAME') }}
          ServerAlias {{ lookup('env','ALIAS') }}.{{ lookup('env','SERVER_NAME') }}
          DocumentRoot /var/www/{{ lookup('env','ALIAS') }}.{{ lookup('env','SERVER_NAME') }}/public_html
        </VirtualHost>
        
  tasks:
  - name: Enabling the new Virtual Host configuration
    command: /bin/ln -s "/etc/httpd/sites-available/{{ lookup('env','ALIAS') }}.{{ lookup('env','SERVER_NAME') }}.conf" \
                        "/etc/httpd/sites-enabled/{{ lookup('env','ALIAS') }}.{{ lookup('env','SERVER_NAME') }}.conf"
                        
  tasks:                        
  - name: Restart Apache httpd to take configurations
    service:
      name: httpd 
      state: restarted
    become: true
